name: cargo-deny
on:
  workflow_dispatch:
  pull_request:
    paths: ['Cargo.toml','Cargo.lock','deny.toml']
  push:
    branches: [main]
    paths: ['Cargo.toml','Cargo.lock','deny.toml']
jobs:
  cargo-deny:
    uses: KooshaPari/phenotype-tooling/.github/workflows/reusable/cargo-deny.yml@42f1c29b495fa2a9acbbc3eeff0aaad5fa76aad7
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

