name: Cargo Machete
on:
  workflow_dispatch:

permissions:
  contents: read


on:
  push:
  pull_request:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-unused-dependencies:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v4
      - uses: taiki-e/install-action@db5fb34fa772531a3ece57ca434f579eb334e0fb
        with:
          tool: cargo-machete

      - name: Run cargo machete
        run: cargo machete .
