name: Cargo Machete
on:
  workflow_dispatch:

permissions:
  contents: read


on:
  push:
  pull_request:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-unused-dependencies:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4
      - uses: taiki-e/install-action@9e1e5806d4a4822de933115878265be9aaa786d9
        with:
          tool: cargo-machete

      - name: Run cargo machete
        run: cargo machete .
